import { Archive, Database, History, Lightbulb } from 'lucide-react'

export default function UtilityTab({ kind, learnedPatterns = [], recommendations = [], sessions = [], backup, onClose }) {
  const config = { memory: ['AI 记忆', 'AI 从你的表达里沉淀出的长期线索', Lightbulb], recommendations: ['推荐记录', '最近三十天的建议与结果', Archive], history: ['会话历史', '每次对话的摘要与时间范围', History], backup: ['数据备份', '导出或恢复你的专注树', Database] }[kind] || ['工具', '', Database]
  return <div className="ft-utility-tab"><div className="ft-drawer-intro"><div><span className="ft-eyebrow">ACCOUNT / {kind.toUpperCase()}</span><h1>{config[0]}</h1><p>{config[1]}</p></div><button type="button" className="ft-quiet-button" onClick={onClose}>关闭</button></div>{kind === 'memory' ? <MemoryList patterns={learnedPatterns} /> : kind === 'recommendations' ? <RecommendationList items={recommendations} /> : kind === 'history' ? <HistoryList items={sessions} /> : <BackupActions backup={backup} />}</div>
}

function MemoryList({ patterns }) { return <div className="ft-utility-list">{patterns.length ? patterns.map((pattern, index) => <div className="ft-utility-row" key={pattern.id || index}><Lightbulb size={15} /><span>{pattern.observation || pattern.text || '未命名记忆'}</span><small>{pattern.topic || '长期'}</small></div>) : <UtilityEmpty icon={Lightbulb} text="还没有沉淀的记忆。和 AI 多聊聊你的工作习惯。" />}</div> }
function RecommendationList({ items }) { return <div className="ft-utility-list">{items.length ? items.slice(0, 30).map((item, index) => <div className="ft-utility-row" key={item.id || index}><Archive size={15} /><span>{item.message || item.reply || '一条推荐'}</span><small>{item.derived_outcome || item.outcome || '待办'}</small></div>) : <UtilityEmpty icon={Archive} text="还没有推荐记录。" />}</div> }
function HistoryList({ items }) { return <div className="ft-utility-list">{items.length ? items.map((item, index) => <div className="ft-utility-row" key={item.session_id || index}><History size={15} /><span>{item.summary || '未命名会话'}</span><small>{item.count || 0} 条</small></div>) : <UtilityEmpty icon={History} text="还没有历史会话。" />}</div> }
function BackupActions({ backup }) { return <div className="ft-utility-list"><div className="ft-backup-card"><Database size={18} /><div><strong>本地自动备份</strong><span>{backup?.lastAuto ? `上次自动备份：${new Date(backup.lastAuto).toLocaleString('zh-CN')}` : '自动备份会保存在浏览器本地。'}</span></div></div><button type="button" className="ft-primary-button" onClick={backup?.exportToFile}>导出 JSON 数据</button><label className="ft-upload-button">从文件恢复<input type="file" accept="application/json" onChange={event => backup?.restoreFromFile?.(event.target.files?.[0])} /></label></div> }
function UtilityEmpty({ icon: Icon, text }) { return <div className="ft-utility-empty"><Icon size={24} /><span>{text}</span></div> }
